version: '3'
services:
  postgres:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password!
      TZ: Asia/Tokyo
    volumes:
      - ./db/pq:/docker-entrypoint-initdb.d
    ports:
      - 5555:5432
